-- users
create table users (
  id uuid primary key,
  nickname varchar(24) not null,
  provider varchar(10) not null,
  created_at timestamp with time zone not null
);

-- sessions
create table sessions (
  id uuid primary key,
  user_id uuid not null,
  start_at timestamp with time zone not null,
  end_at   timestamp with time zone,
  final_score int,
  device_info text,
  created_at timestamp with time zone not null,
  constraint fk_sessions_user
    foreign key (user_id) references users(id) on delete cascade
);

-- scores
create table scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  session_id uuid not null,
  score int not null,
  occurred_at timestamp with time zone not null,
  constraint uq_scores_session unique (session_id),
  constraint fk_scores_user foreign key (user_id) references users(id) on delete cascade,
  constraint fk_scores_session foreign key (session_id) references sessions(id) on delete cascade
);

create index idx_scores_score_time on scores (score desc, occurred_at desc);
